### ISSUE TITLE
web에 종속적인 요소들 adaptor로 옮기기

### ISSUE THREAD

**Issue by Taewoongjung** [Taewoongjung/Doseoro_Java#38]
# Issue:🔨 REFACTOR
web에 종속적인 요소(error 헨들러, database 등)들 adaptor로 옮기기

## To-do
- [x] 컨트롤러에 종속성 확인
- [x] web 종속적인 요소들 adaptor로 옮기기 
- [x] 인터페이스 네이밍 'I' 빼기
